nelmio_api_doc:
    documentation:
        info:
            title: Localize API
            description: This is the documentation of the Localize API!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!(doc|_)) # Accepts routes under /api except /api/doc
